=== Keshabkjha/Web-Technology-Training-NIET/Programs/Program26.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="studentProfile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personalInformation">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="age" type="xs:string" />
                            <xs:element name="degree" type="xs:string" />
                            <xs:element name="university" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="skills">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="skill" maxOccurs="unbounded" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="hobbies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hobby" maxOccurs="unbounded" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Keshabkjha/Web-Technology-Training-NIET/Programs/Program26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Design a XML document that describe the well-formed XML document -->
<studentProfile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="Program26.xsd">
    <personalInformation>
        <name>Keshab Kumar</name>
        <age>21</age>
        <degree>Computer Science and Engineering</degree>
        <university>Noida Institute of Engineering and Technology</university>
    </personalInformation>
    
    <skills>
        <skill>HTML</skill>
        <skill>CSS</skill>
        <skill>JavaScript</skill>
    </skills>
    
    <hobbies>
        <hobby>Playing Harmonium</hobby>
        <hobby>Land Surveying</hobby>
    </hobbies>
</studentProfile>
